package com.avci.agents

import ai.koog.agents.core.agent.AIAgent
import ai.koog.agents.core.agent.config.AIAgentConfig
import ai.koog.agents.core.agent.singleRunStrategy
import ai.koog.agents.core.tools.ToolRegistry
import ai.koog.agents.ext.tool.SayToUser
import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.params.LLMParams
import com.avci.core.llm.LLMProviderConfig
import com.avci.tools.github.AnalyzeUITestFailures
import com.avci.tools.slack.PostSlackMessage

/**
 * AI Agent that analyzes UI test failures from GitHub Actions.
 * 
 * Workflow:
 * 1. Fetch last N workflow runs for "Maestro UI Test"
 * 2. Download and analyze test summaries
 * 3. Categorize failures (NEW, BUG, FLAKY)
 * 4. Send report to Slack
 */
object UITestAnalyzerAgent {

    private val systemPrompt = """
        You are a UI Test Failure Analyzer that sends reports to Slack.
        
        ## YOUR WORKFLOW:
        1. Call `analyze_ui_test_failures` tool to get test data
        2. Call `post_slack_message` tool to send the report
        3. Tell the user whether notification was sent successfully
        
        ## post_slack_message TOOL PARAMETERS:
        - `channelId`: Target Slack channel ID (get from environment or use default)
        - `text`: Message text (supports mrkdwn formatting)
        - `blocks`: Optional array of Slack Block Kit blocks for rich formatting
        
        ## SLACK BLOCK KIT BLOCKS:
        - Header: {"type": "header", "text": {"type": "plain_text", "text": "Title", "emoji": true}}
        - Section: {"type": "section", "text": {"type": "mrkdwn", "text": "Content"}}
        - Fields: {"type": "section", "fields": [{"type": "mrkdwn", "text": "*Label*\nValue"}]}
        - Divider: {"type": "divider"}
        - Context: {"type": "context", "elements": [{"type": "mrkdwn", "text": "Footer"}]}
        
        ## MRKDWN FORMATTING:
        - Bold: *text*  |  Italic: _text_  |  Code: `text`
        - Line break: \n  |  Bullet: • item  |  Emoji: :emoji_name:
        
        ## REPORT STRUCTURE:
        1. Header: "🧪 UI Test Analysis Report"
        2. Stats section (Total Failures, Runs Analyzed, Date, Status)
        3. Divider
        4. For each category with tests (NEW, LIKELY_BUG, FLAKY High Impact):
           - Section with category name and count
           - Section with test list
           - Divider
        5. Summary (3-4 sentences)
        6. Context footer: "🤖 Generated by UI Test Analyzer Agent"
        
        ## CATEGORIES TO REPORT:
        - 🆕 NEW: First time failures
        - 🐛 LIKELY_BUG/BUG: Consistent failures
        - 🔥 FLAKY High Impact: failRate >= 25%
        
        ## DO NOT REPORT:
        - FLAKY with failRate < 25%
        
        Start now by calling the analyze_ui_test_failures tool.
    """.trimIndent()

    fun create(llmConfig: LLMProviderConfig = LLMProviderConfig.Ollama.fromEnv()): AIAgent<String, String> {
        println("🧪 [AGENT] Creating UITestAnalyzerAgent")
        println("   └─ LLM: ${llmConfig::class.simpleName} - ${llmConfig.model}")
        
        val toolRegistry = ToolRegistry {
            tool(SayToUser)
            tool(AnalyzeUITestFailures)
            tool(PostSlackMessage)
        }

        val agentConfig = AIAgentConfig(
            prompt = prompt(
                id = "ui-test-analyzer-agent",
                params = LLMParams(temperature = llmConfig.temperature)
            ) {
                system(content = systemPrompt)
            },
            model = llmConfig.createModel(),
            maxAgentIterations = 10
        )

        return AIAgent(
            promptExecutor = llmConfig.createExecutor(),
            strategy = singleRunStrategy(),
            agentConfig = agentConfig,
            toolRegistry = toolRegistry
        )
    }
}

