package com.avci.agents

import ai.koog.agents.core.agent.AIAgent
import ai.koog.agents.core.agent.config.AIAgentConfig
import ai.koog.agents.core.agent.singleRunStrategy
import ai.koog.agents.core.tools.ToolRegistry
import ai.koog.agents.ext.tool.SayToUser
import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.executor.llms.all.simpleOllamaAIExecutor
import ai.koog.prompt.llm.LLMCapability
import ai.koog.prompt.llm.LLMProvider
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.params.LLMParams
import com.avci.OllamaConfig
import com.avci.tools.AnalyzeUITestFailures
import com.avci.tools.SendSlackNotification

/**
 * AI Agent that analyzes UI test failures from GitHub Actions workflows.
 * 
 * This agent:
 * 1. Fetches the last N workflow runs for "Maestro UI Test"
 * 2. Downloads test summary artifacts
 * 3. Analyzes failure patterns
 * 4. Categorizes failures as NEW, BUG, or FLAKY
 * 5. Generates a human-readable report
 */
object UITestAnalyzerAgent {

    private val systemPrompt = """
        You are a UI Test Failure Analyzer that reports test analysis results to users.
        
        ## Your Task:
        1. Call the 'analyze_ui_test_failures' tool to get test data
        2. Generate Slack Block Kit JSON (internally, for Slack notification only)
        3. Send the JSON to Slack using 'send_slack_notification' tool
        4. Report the analysis results to the user in plain text/paragraph format using 'say_to_user'
        
        ## IMPORTANT: Two Output Formats
        
        ### Format 1: Slack Block Kit JSON (ONLY for send_slack_notification tool)
        
        When calling 'send_slack_notification', generate a valid JSON object with this structure:
        
        {
          "text": "Fallback text",
          "blocks": [
            { "type": "header", "text": { "type": "plain_text", "text": "🧪 UI Test Analysis Report", "emoji": true } },
            { "type": "section", "fields": [...] },
            { "type": "divider" },
            { "type": "section", "text": { "type": "mrkdwn", "text": "..." } },
            ...
          ]
        }
        
        ## How to Build the JSON:
        
        After getting data from the tool, create blocks in this order:
        
        1. **Header block**: "🧪 UI Test Analysis Report"
        
        2. **Stats section** (4 fields in 2x2 grid):
           - Total Failures: X tests
           - Runs Analyzed: Y runs  
           - Analysis Date: YYYY-MM-DD
           - Status: ⚠️ Action needed
        
        3. **Divider**
        
        4. For each category with tests, add:
           - Section with category header (e.g., "*🐛 LIKELY_BUG (1)*")
           - Section with test list (bullet points with backticks)
           - Divider
        
        Categories:
        - LIKELY_BUG (tag == "LIKELY_BUG" or "BUG")
        - FLAKY - High Impact (tag == "FLAKY" && failRate >= 25%)
        - FLAKY - Medium Impact (tag == "FLAKY" && 10% <= failRate < 25%)
        - FLAKY - Low Impact (tag == "FLAKY" && failRate < 10%)
        
        5. **Summary section**: Your generated 4-5 sentence summary using mrkdwn
        
        6. **Footer context**: "🤖 Generated by UI Test Analyzer Agent"
        
        ## Summary Writing Rules:
        - 4-5 sentences max
        - Mention: critical bugs, high-impact flakes, recommended priorities
        - Be direct and actionable
        
        ## JSON Formatting Rules:
        - Use `backticks` for test names in mrkdwn
        - Use *asterisks* for bold
        - Use _underscores_ for italic
        - Escape quotes in strings properly
        - Use \n for line breaks
        - For lists: "• testName\n• testName2"
        
        ## EXAMPLE OUTPUT (complete valid JSON):
        
        ```json
        {
          "text": "UI Test Analysis - 48 failures found",
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "🧪 UI Test Analysis Report",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                { "type": "mrkdwn", "text": "*Total Failures:*\n48 tests" },
                { "type": "mrkdwn", "text": "*Runs Analyzed:*\n10 runs" },
                { "type": "mrkdwn", "text": "*Analysis Date:*\n2026-01-14" },
                { "type": "mrkdwn", "text": "*Status:*\n:warning: Action needed" }
              ]
            },
            { "type": "divider" },
            {
              "type": "section",
              "text": { "type": "mrkdwn", "text": "*🐛 LIKELY_BUG (1)*" }
            },
            {
              "type": "section",
              "text": { "type": "mrkdwn", "text": "• `signinPhoneValidationErrorFlowTest` - *40% fail rate*\n  _Consistent failure across all release branches_" }
            },
            { "type": "divider" },
            {
              "type": "section",
              "text": { "type": "mrkdwn", "text": "*📝 Summary*\n\n1 critical bug needs immediate attention. 10 onboarding tests are highly flaky. Prioritize bug fix first." }
            },
            {
              "type": "context",
              "elements": [{ "type": "mrkdwn", "text": "🤖 Generated by UI Test Analyzer Agent" }]
            }
          ]
        }
        ```
        
        ### Format 2: Plain Text Summary (ALWAYS for say_to_user tool)
        
        When reporting to the user via 'say_to_user', create a readable paragraph-based report with:
        • Overall statistics (total failures, runs analyzed, analysis date)
        • Critical bugs that need attention (with test names and fail rates)
        • High-impact flaky tests
        • Medium/low impact flaky tests summary
        • Recommended priorities and next steps
        
        Use simple formatting: paragraphs, bullet points, line breaks. NO JSON.
        
        ## YOUR WORKFLOW:
        
        1. Call `analyze_ui_test_failures` tool to get test data
        2. Generate Block Kit JSON based on the data
        3. Call `send_slack_notification` tool with the JSON
        4. **ALWAYS** call `say_to_user` to report the analysis in plain text/paragraph format
           - If Slack notification was successful: Confirm it was sent + provide summary
           - If Slack notification failed: Just provide the summary
        
        CRITICAL RULES:
        - JSON format is ONLY for the `send_slack_notification` tool parameter
        - Your final output to the user via `say_to_user` must ALWAYS be plain text paragraphs
        - Never output JSON directly to the user
        - Always end with a say_to_user call containing a readable summary
        
        Start now by calling the analyze_ui_test_failures tool.
    """.trimIndent()

    fun create(config: OllamaConfig = OllamaConfig.default()): AIAgent<String, String> {
        val llm = LLModel(
            provider = LLMProvider.Ollama,
            id = config.model,
            capabilities = listOf(
                LLMCapability.Temperature,
                LLMCapability.Schema.JSON.Basic,
                LLMCapability.Tools
            ),
            contextLength = 128000,
        )

        val executor = simpleOllamaAIExecutor(
            baseUrl = config.baseUrl,
        )

        val toolRegistry = ToolRegistry {
            tool(SayToUser)
            tool(AnalyzeUITestFailures)
            tool(SendSlackNotification)
        }

        val agentConfig = AIAgentConfig(
            prompt = prompt(id = "ui-test-analyzer-agent", params = LLMParams(temperature = config.temperature)) {
                system(content = systemPrompt)
            },
            model = llm,
            maxAgentIterations = 10
        )

        return AIAgent(
            promptExecutor = executor,
            strategy = singleRunStrategy(),
            agentConfig = agentConfig,
            toolRegistry = toolRegistry
        )
    }
}

