package com.avci.agents

import ai.koog.agents.core.agent.AIAgent
import ai.koog.agents.core.agent.config.AIAgentConfig
import ai.koog.agents.core.agent.singleRunStrategy
import ai.koog.agents.core.tools.ToolRegistry
import ai.koog.agents.ext.tool.SayToUser
import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.executor.llms.all.simpleOllamaAIExecutor
import ai.koog.prompt.llm.LLMCapability
import ai.koog.prompt.llm.LLMProvider
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.params.LLMParams
import com.avci.OllamaConfig
import com.avci.tools.AnalyzeUITestFailures
import com.avci.tools.SendSlackNotification

/**
 * AI Agent that analyzes UI test failures from GitHub Actions workflows.
 * 
 * This agent:
 * 1. Fetches the last N workflow runs for "Maestro UI Test"
 * 2. Downloads test summary artifacts
 * 3. Analyzes failure patterns
 * 4. Categorizes failures as NEW, BUG, or FLAKY
 * 5. Generates a human-readable report
 */
object UITestAnalyzerAgent {

    private val systemPrompt = """
        You are a UI Test Failure Analyzer that sends reports to Slack.
        
        ## YOUR WORKFLOW:
        1. Call `analyze_ui_test_failures` tool to get test data
        2. Call `send_slack_notification` tool with `text` and `blocks` parameters
        3. Tell the user whether notification was sent successfully
        
        ## send_slack_notification TOOL PARAMETERS:
        
        - `text`: Fallback text shown in notifications (e.g., "UI Test Report - 5 failures")
        - `blocks`: Array of Slack Block Kit blocks
        
        ## SLACK BLOCK KIT BLOCKS:
        
        Block types you can use:
        - Header: {"type": "header", "text": {"type": "plain_text", "text": "Title", "emoji": true}}
        - Section with text: {"type": "section", "text": {"type": "mrkdwn", "text": "Content"}}
        - Section with fields: {"type": "section", "fields": [{"type": "mrkdwn", "text": "*Label*\nValue"}]}
        - Divider: {"type": "divider"}
        - Context: {"type": "context", "elements": [{"type": "mrkdwn", "text": "Footer text"}]}
        
        ## MRKDWN FORMATTING:
        - Bold: *text*
        - Italic: _text_
        - Code: `text`
        - Line break: \n
        - Bullet: • item
        - Emoji: :emoji_name: (e.g., :warning:, :bug:, :white_check_mark:)
        
        ## REPORT STRUCTURE:
        
        Build blocks in this order:
        1. Header: "🧪 UI Test Analysis Report"
        2. Stats section with fields (Total Failures, Runs Analyzed, Date, Status)
        3. Divider
        4. For each category with tests:
           - Section with category name and count
           - Section with test list
           - Divider
        5. Summary section (3-4 sentences about findings and recommendations)
        6. Context footer: "🤖 Generated by UI Test Analyzer Agent"
        
        ## CATEGORIES TO REPORT (only include these):
        - 🆕 NEW: Tests tagged as "NEW" (first time failures)
        - 🐛 LIKELY_BUG: Tests tagged as "LIKELY_BUG" or "BUG" (consistent failures)
        - 🔥 FLAKY High Impact: Tests tagged as "FLAKY" with failRate >= 25%
        
        ## DO NOT REPORT:
        - FLAKY Medium Impact (10% <= failRate < 25%) - skip these
        - FLAKY Low Impact (failRate < 10%) - skip these
        
        If there are no NEW, BUG, or high-impact FLAKY tests, report "No critical issues found" in summary.
        
        Start now by calling the analyze_ui_test_failures tool.
    """.trimIndent()

    fun create(config: OllamaConfig = OllamaConfig.default()): AIAgent<String, String> {
        val llm = LLModel(
            provider = LLMProvider.Ollama,
            id = config.model,
            capabilities = listOf(
                LLMCapability.Temperature,
                LLMCapability.Schema.JSON.Basic,
                LLMCapability.Tools
            ),
            contextLength = 128000,
        )

        val executor = simpleOllamaAIExecutor(
            baseUrl = config.baseUrl,
        )

        val toolRegistry = ToolRegistry {
            tool(SayToUser)
            tool(AnalyzeUITestFailures)
            tool(SendSlackNotification)
        }

        val agentConfig = AIAgentConfig(
            prompt = prompt(id = "ui-test-analyzer-agent", params = LLMParams(temperature = config.temperature)) {
                system(content = systemPrompt)
            },
            model = llm,
            maxAgentIterations = 10
        )

        return AIAgent(
            promptExecutor = executor,
            strategy = singleRunStrategy(),
            agentConfig = agentConfig,
            toolRegistry = toolRegistry
        )
    }
}

